from google import genai
from fpdf import FPDF
import os
from datetime import datetime
from typing import Dict, Any, List

class ReportService:
    def __init__(self):
        api_key = os.getenv("GOOGLE_API_KEY")
        # Check for presence and avoid using the placeholder string from .env
        if api_key and "YOUR_GEMINI" not in api_key:
            self.client = genai.Client(api_key=api_key)
            print("Report Engine: Gemini AI Initialized (New SDK).")
        else:
            self.client = None
            print("Report Engine: Warning - GOOGLE_API_KEY missing or placeholder. LLM features disabled.")

    def generate_llm_report(self, species_name: str, species_data: Dict[str, Any], env_context: Dict[str, Any], conservation_plan: List[Dict[str, Any]]) -> str:
        """
        Generates a comprehensive ecological report using LLM with retry logic and fallback.
        """
        import time
        import random

        # Prepare Data Snapshot for LLM
        traits = species_data.get("biological_traits", {})
        pop_history = species_data.get("population_history", [])
        
        prompt = f"""
        Act as a Senior Conservation Biologist for WildSight (an AI-driven biodiversity monitoring platform). 
        Generate a professional, detailed conservation report for: {species_name}.

        [BIOMETRIC DATA]
        - Status: {species_data.get('status')}
        - Estimated Population: {species_data.get('estimated_population')}
        - Kingdom: {traits.get('kingdom')}, Class: {traits.get('class')}
        - Recent Trend: {pop_history[-3:] if pop_history else 'Minimal Data'}

        [ENVIRONMENTAL CONTEXT]
        - Current Risk Score: {env_context.get('risk_score', 0.0)}
        - Habitat Quality (NDVI): {env_context.get('avg_ndvi', 0.0)}
        - Temperature: {env_context.get('avg_temp', 0.0)}C, Rainfall: {env_context.get('avg_rain', 0.0)}mm
        - Human Dev Index: {env_context.get('hdi', 0.0)}
        
        [DETAILED ANALYSIS]
        - Vegetation Trend (Last 5 Days): {env_context.get('veg_trend', 'N/A')}
        - Climate Forecast (Next 5 Years): {env_context.get('climate_trend', 'N/A')}
        - Human Disturbance (Last 5 Years): {env_context.get('dist_trend', 'N/A')}
        
        [AIDED FUTURE OUTLOOK]
        *This section is generated by our internal ML Predictive Model.*
        - Predicted Status in 5 Years: {env_context.get('future_outlook', {}).get('verdict', 'Unknown')}
        - Probability of Endangerment: {env_context.get('future_outlook', {}).get('endangerment_probability', 0.0)}
        - Primary Driver: {env_context.get('future_outlook', {}).get('primary_driver', 'None')}
        - Projected Decline Rate: {env_context.get('future_outlook', {}).get('projected_decline_rateax', 0.0)}% per year

        [CURRENT CONSERVATION PLAN]
        {conservation_plan}

        [REPORT REQUIREMENTS]
        1. **Overview**: State of the species in India and the specific analyzed habitat.
        2. **Cause of Fluctuation**: Detailed geological and meteorological analysis of why population counts are shifting.
        3. **Region-Specific Risks**: Identify stressors based on the environmental data (e.g., Habitat Loss if NDVI is low, or Heatwaves if Temp is high).
        4. **Conservation Recommendations**: Practical, actionable tips for local stakeholders and community engagement strategies.
        5. **Key Trends**: Briefly summarize the 5-day vegetation and 5-year climate/disturbance trends.

        Use Markdown formatting with professional headings. Be specific to this species.
        """
        
        if not self.client:
             print("Report Engine: LLM not configured, using fallback.")
             return self._generate_fallback_report(species_name, species_data, env_context, conservation_plan)

        retries = 3
        for attempt in range(retries):
            try:
                response = self.client.models.generate_content(
                    model='gemini-2.0-flash',
                    contents=prompt
                )
                return response.text
            except Exception as e:
                error_str = str(e)
                print(f"LLM Generation Attempt {attempt+1} Failed: {e}")
                
                # Check for quota errors or service errors to retry
                if "429" in error_str or "503" in error_str or "RESOURCE_EXHAUSTED" in error_str:
                    if attempt < retries - 1:
                        sleep_time = (2 ** attempt) + random.uniform(0, 1)
                        print(f"Retrying in {sleep_time:.2f} seconds...")
                        time.sleep(sleep_time)
                        continue
                
                # If it's not a retryable error or we ran out of retries, break to fallback
                break
        
        print("Report Engine: Switched to Fallback Report due to LLM errors.")
        return self._generate_fallback_report(species_name, species_data, env_context, conservation_plan)

    def _generate_fallback_report(self, species_name: str, species_data: Dict[str, Any], env_context: Dict[str, Any], conservation_plan: List[Dict[str, Any]]) -> str:
        """
        Generates a structured template-based report when LLM is unavailable.
        """
        traits = species_data.get("biological_traits", {})
        future = env_context.get('future_outlook', {})
        
        report = f"""# WildSight Conservation Report: {species_name}

## 1. Overview
**Status:** {species_data.get('status')}
**Estimated Population:** {species_data.get('estimated_population')}

This report serves as an automated analysis of the *{species_name}* population, a member of the {traits.get('class')} class. The current risk assessment score is **{env_context.get('risk_score', 0.0)}/1.0**.

## 2. Environmental Context
The habitat analysis indicates the following conditions:
- **Habitat Quality (NDVI):** {env_context.get('avg_ndvi', 0.0)}
- **Average Temperature:** {env_context.get('avg_temp', 0.0)}°C
- **Rainfall:** {env_context.get('avg_rain', 0.0)}mm
- **Human Disturbance Index:** {env_context.get('hdi', 0.0)}

## 3. Future Outlook (ML Prediction)
Our predictive models forecast the following for the next 5 years:
- **Predicted Status:** {future.get('verdict', 'Unknown')}
- **Endangerment Probability:** {future.get('endangerment_probability', 0.0)}
- **Projected Decline Rate:** {future.get('projected_decline_rateax', 0.0)}% per year
- **Primary Driver of Change:** {future.get('primary_driver', 'None')}

## 4. Conservation Plan
The following actions are recommended based on current data:
"""
        for plan in conservation_plan:
            report += f"- **{plan.get('action_type', 'Action')}:** {plan.get('description', 'No description available.')}\n"
            
        report += "\n## 5. Key Trends\n"
        report += f"- **Vegetation:** {env_context.get('veg_trend', 'N/A')}\n"
        report += f"- **Climate:** {env_context.get('climate_trend', 'N/A')}\n"
        report += f"- **Disturbance:** {env_context.get('dist_trend', 'N/A')}\n"
        
        report += "\n> *Note: This report was generated using a structured fallback template because the AI analysis engine was temporarily unavailable.*"
        
        return report

    def _safe_text(self, text: str) -> str:
        """
        Ensures text is safe for FPDF (Latin-1 compatible).
        Replaces unsupported characters (like emojis or complex unicode) with '?'.
        """
        # Dictionary of common replacements to avoid ugly '?'
        replacements = {
            "’": "'",
            "‘": "'",
            "“": '"',
            "”": '"',
            "–": "-",
            "—": "-",
            "…": "...",
        }
        for k, v in replacements.items():
            text = text.replace(k, v)
            
        return text.encode('latin-1', 'replace').decode('latin-1')

    def generate_pdf_report(self, species_name: str, report_text: str) -> str:
        """
        Converts the markdown report text into a professional PDF.
        """
        try:
            pdf = FPDF()
            pdf.add_page()
            
            # Title
            pdf.set_font("helvetica", "B", 16)
            pdf.cell(0, 10, self._safe_text(f"WildSight Conservation Report: {species_name}"), ln=True, align='C')
            pdf.set_font("helvetica", "I", 10)
            pdf.cell(0, 10, self._safe_text(f"Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"), ln=True, align='C')
            pdf.ln(10)
            
            # Body
            pdf.set_font("helvetica", size=11)
            
            lines = report_text.split('\n')
            for line in lines:
                try:
                    if line.startswith("# "):
                        pdf.set_font("helvetica", "B", 14)
                        pdf.cell(0, 10, self._safe_text(line.replace("# ", "")), ln=True)
                        pdf.set_font("helvetica", size=11)
                    elif line.startswith("## "):
                        pdf.set_font("helvetica", "B", 12)
                        pdf.cell(0, 8, self._safe_text(line.replace("## ", "")), ln=True)
                        pdf.set_font("helvetica", size=11)
                    elif line.startswith("**") and "**" in line[2:]: 
                         clean_line = line.replace("**", "")
                         pdf.multi_cell(0, 6, txt=self._safe_text(clean_line))
                    else:
                        clean_line = line.replace("**", "").replace("* ", "- ")
                        pdf.multi_cell(0, 6, txt=self._safe_text(clean_line))
                except Exception as e:
                    print(f"PDF Line Error: {e}")
                
            reports_dir = os.path.abspath(os.path.join(os.getcwd(), "exports", "reports"))
            os.makedirs(reports_dir, exist_ok=True)
            
            filename = f"WildSight_{species_name}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
            output_path = os.path.join(reports_dir, filename)
            
            pdf.output(output_path)
            return output_path
        except Exception as e:
            print(f"PDF Generation Error: {e}")
            return None

report_service = ReportService()
